### ISSUE TITLE
Groovy file

### ISSUE THREAD

**Issue by claudiogbarreto** [adxsoft/MapInsight-Addon#2]
Thanks a lot for your well done job.

After installing the addon, the script file (in C:\Users\XXXX\AppData\Roaming\Freeplane\1.8.x\addons\MapInsight\scripts\MapInsight.groovy) does not contain a sript, but the readme.md file. 

So, when I try to run the addon I get an error message.

When I change the content of the file to the script, It works finely.

**Comment by adxsoft** [comment]
Thanks for the feedback.
Have now fixed the Mapsight v1.2 add on.
